import Head from "next/head";
import { useState } from "react";

import Display from "@/components/Display";
import WordBank from "@/components/WordBank";

import characters from "@/data/characters.json";
import Character from "@/data/characters";

const charSet = new Set<string>();
for (const char of characters as Character[]) {
    charSet.add(char.glyph);
    if (char.simplified) {
        charSet.add(char.simplified);
    }
    if (char.traditional) {
        charSet.add(char.traditional);
    }
}

export default function Home() {
    const [text, setText] = useState("");
    const addChar = (char: string) => {
        setText(text + char);
    };

    return (
        <>
            <Head>
                <title>wen</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <WordBank characters={characters} addChar={addChar} />
                <div id="inputanddisplay">
                    <section id="input">
                        <h2>input</h2>
                        <p>
                            write chinese text to see it displayed in my
                            calligraphy, ransom note-style
                        </p>
                        <textarea
                            value={text}
                            onChange={(e) => setText(e.target.value)}
                        />
                    </section>
                    <Display text={text} charSet={charSet} />
                </div>
            </main>
        </>
    );
}
