import Head from "next/head";
import styles from "@/styles/Home.module.css";

import WordBank from "@/components/WordBank";

import path from "path";
import { readdir } from "node:fs/promises";

export default function Home({ characters }: { characters: string[] }) {
    return (
        <>
            <Head>
                <title>wen</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div></div>
                <WordBank characters={characters} />
            </main>
        </>
    );
}

export async function getStaticProps() {
    const characters = await readdir(path.join(process.cwd(), "public/c"));
    return {
        props: {
            characters,
        },
    };
}
